bank/urls.py
from django.conf import settings
from django.conf.urls.i18n import i18n_patterns
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.utils.translation import gettext_lazy as _

urlpatterns = [
    path('rosetta/', include('rosetta.urls')),
    path('api/', include('client.api.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
    path('', include('guest.urls')),
]

urlpatterns += i18n_patterns(
    path(_('admin/'), admin.site.urls),
    path(_('client/'), include('client.urls')),
    path(_('payment/'), include('transactions.urls')),
    path(_('transfer/'), include('transactions.urls')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

transactions/urls.py
from django.urls import path
from django.utils.translation import gettext_lazy as _

from . import views

urlpatterns = [
    path('', views.transfer, name='payments'),
    path(_('incoming/'), views.transfer_inc, name='transfer_inc'),
    path(_('outgoing/'), views.transfer_out, name='transfer_out'),
    path(_('client/<slug:account_slug>/'), views.export_to_csv, name='export_to_csv'),
    path('<int:id>/', views.transfer_detail, name='transfer_detail'),
    path('<int:transaction_id>/pdf/', views.transaction_pdf, name='transaction_pdf'),
]

transactions/models.py
from decimal import Decimal

from django.core.validators import MinValueValidator
from django.db import models
from django.urls import reverse
from django.utils.translation import gettext_lazy as _

from client.models import Account


class Transaction(models.Model):
    class Type(models.TextChoices):
        INCOMING = "INC", _("Incomming")
        OUTGOING = "OUT", _("Outgoing")
        PAYMENT = "PAY", _("Payment")

    agent = models.CharField(_('agent'), max_length=120)
    amount = models.DecimalField(
        _('amount'),
        validators=[MinValueValidator(Decimal('0.01'))],
        max_digits=10,
        decimal_places=2,
    )
    concept = models.CharField(_('concept'), max_length=120, blank=True)
    timestamp = models.DateTimeField(auto_now_add=True)
    account = models.ForeignKey(Account, related_name='transactions', on_delete=models.CASCADE)
    kind = models.CharField(_('kind'), max_length=3, choices=Type.choices)

    def __str__(self):
        static_text = _('Transaction ')
        return f'{static_text}{self.id} - {self.amount}'

    class Meta:
        indexes = [models.Index(fields=['-timestamp'])]
        ordering = ['-timestamp']

    def get_absolute_url(self):
        return reverse('transfer_detail', args=[self.id])


class Comission(models.Model):
    class Type(models.TextChoices):
        INCOMING = "INC", _("Incomming Transaction")
        OUTGOING = "OUT", _("Outgoing Transaction")
        PAYMENT = "PAY", _("Payment")

    kind = models.CharField(_('kind'), max_length=3, choices=Type.choices)
    transfer = models.ForeignKey(Transaction, related_name='comissions', on_delete=models.CASCADE)
    amount = models.DecimalField(
        validators=[MinValueValidator(Decimal('0.01'))],
        decimal_places=2,
        max_digits=10,
        verbose_name=_('amount'),
    )

transactions/forms.py
from django import forms
from django.utils.translation import gettext_lazy as _

from .models import Transaction


class TransactionForm(forms.ModelForm):
    account = forms.CharField(label=_('Recipient'), max_length=120)

    class Meta:
        model = Transaction
        fields = ['concept', 'amount', 'agent']

transactions/views.py
import csv
import json
from decimal import Decimal
from typing import Any

import requests
import weasyprint
from django import forms
from django.conf import settings
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import get_object_or_404, render
from django.template.loader import render_to_string
from django.utils.translation import gettext_lazy as _
from django.views.decorators.csrf import csrf_exempt

from client.models import Account, Card, Client

from .forms import TransactionForm
from .models import Comission, Transaction
from .utils import calc_comission


@csrf_exempt
def transfer(request):
    data = json.loads(request.body)
    if {'business', 'ccc', 'pin', 'amount'} == set(data.keys()):
        if data['ccc'][:2] != settings.BANK_CARD_CODE:
            error = _('Unrecognized card')
            return render(
                request,
                'transactions/transaction/error.html',
                {'error': error},
            )
        card_id = int(data['ccc'][3:])
        if card := get_object_or_404(Card, id=card_id, pin=data['pin'], status=Card.States.ACTIVE):
            account = card.account
            amount = Decimal(data['amount'])
            comission_amount = calc_comission(
                amount,
                Comission.Type.PAYMENT,
                settings.COMISSION_TABLE,
            )
            if amount + comission_amount <= account.balance:
                account.balance -= amount + comission_amount
                new_transaction = Transaction(
                    agent=data['business'],
                    amount=data['amount'],
                    concept='payment',
                    account=account,
                    kind=Transaction.Type.PAYMENT,
                )
                account.save()
                new_transaction.save()
                new_comission = Comission(
                    kind=Comission.Type.PAYMENT,
                    transfer=new_transaction,
                    amount=comission_amount,
                )
                new_comission.save()
            return HttpResponse()
        else:
            error = _('Unable to operate with the given card')
            return render(
                request,
                'transactions/transaction/error.html',
                {'error': error},
            )
    else:
        error = _('Data not consistent with request')
        return render(
            request,
            'transactions/transaction/error.html',
            {'error': error},
        )


@csrf_exempt
def transfer_inc(request):
    data = json.loads(request.body)
    if {'sender', 'cac', 'concept', 'amount'} <= set(data.keys()):
        account_id = int(data['cac'][3:])
        if account := get_object_or_404(Account, id=account_id, status=Account.States.ACTIVE):
            amount = Decimal(data['amount'])
            comission_amount = calc_comission(
                amount,
                Comission.Type.INCOMING,
                settings.COMISSION_TABLE,
            )
            account.balance += amount - comission_amount
            new_transaction = Transaction(
                agent=data['sender'],
                amount=amount,
                concept=data['concept'],
                account=account,
                kind=Transaction.Type.INCOMING,
            )
            account.save()
            new_transaction.save()
            new_comission = Comission(
                kind=Comission.Type.INCOMING,
                transfer=new_transaction,
                amount=comission_amount,
            )
            new_comission.save()

            return HttpResponse()
        else:
            error = _('Unable to operate with the given account')
            return render(
                request,
                'transactions/transaction/error.html',
                {'error': error},
            )
    else:
        error = _('Data not consistent with request')
        return render(
            request,
            'transactions/transaction/error.html',
            {'error': error},
        )


@csrf_exempt
@login_required
def transfer_out(request):
    if request.method == 'POST':
        form = TransactionForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            agent_type, bank_id = cd['account'][:2]
            if agent_type == 'A' and int(bank_id) < len(settings.BANK_DATA):
                bank_url = settings.BANK_DATA[int(bank_id)]['url'] + '/transfer/incoming/'
            else:
                error = _('Unregistered entity')
                return render(
                    request,
                    'transactions/transaction/error.html',
                    {'error': error},
                )
            account_id = cd['agent']
            account = get_object_or_404(Account, id=account_id)
            amount = cd['amount']
            comission_amount = calc_comission(
                amount,
                Comission.Type.OUTGOING,
                settings.COMISSION_TABLE,
            )
            if amount + comission_amount > account.balance:
                error = _("Amount exceeds account\'s available money")
                return render(
                    request,
                    'transactions/transaction/error.html',
                    {'error': error},
                )
            data = {
                'sender': account.alias,
                'cac': cd['account'],
                'concept': cd['concept'],
                'amount': str(amount),
            }
            response = requests.post(bank_url, json=data)
            if response.status_code == 200:
                account.balance -= amount + comission_amount
                new_transaction = Transaction(
                    agent=account.alias,
                    amount=amount,
                    concept=data['concept'],
                    account=account,
                    kind=Comission.Type.OUTGOING,
                )
                new_comission = Comission(
                    kind=Comission.Type.OUTGOING, transfer=new_transaction, amount=comission_amount
                )
                account.save()
                new_transaction.save()
                new_comission.save()
                return render(
                    request,
                    'transactions/transaction/done.html',
                    {'form': form, 'transaction': new_transaction},
                )
        messages.error(request, _('Unable to reach the recipient.'))
        return render(request, 'transactions/transaction/create.html', {'form': form})
    else:
        user = Client.objects.get(user=request.user)
        if accounts := user.accounts.filter(status=Account.States.ACTIVE):
            form = TransactionForm()
            form.fields['agent'] = forms.ModelChoiceField(label=_('Agent'), queryset=accounts)
        else:
            messages.error(
                request, _('You must have an active account in order to make a transaction.')
            )
            return HttpResponseRedirect('/client/')
    return render(request, 'transactions/transaction/create.html', {'form': form})


def get_queryset(request):
    client = get_object_or_404(Client, user=request.user)
    if 'account_id' in request.GET.keys():
        account = get_object_or_404(Account, id=request.GET.get('account_id'), user=client.id)
        queryset = account.transactions.all()
    else:
        accounts = client.accounts.all()
        queryset = Transaction.objects.filter(account__in=accounts)
    return queryset


@login_required
def transfer_detail(request, id):
    transaction = get_object_or_404(Transaction, id=id)
    return render(request, 'transactions/transaction/detail.html', {'transaction': transaction})


@login_required
def transaction_pdf(request, transaction_id):
    transaction = get_object_or_404(Transaction, id=transaction_id)
    html = render_to_string('transactions/transaction/pdf.html', {'transaction': transaction})

    response = HttpResponse(content_type='application/pdf')
    response['Content-Disposition'] = f'filename=transaction_{transaction_id}.pdf'
    weasyprint.HTML(string=html, base_url=request.build_absolute_uri()).write_pdf(response)
    return response


def export_to_csv(request, account_slug):
    target_account = get_object_or_404(Account, slug=account_slug)
    queryset = get_queryset(request).filter(account=target_account)
    content_disposition = 'attachment; filename=movements.csv'
    response = HttpResponse(content_type='text/csv')
    response['Content-Disposition'] = content_disposition
    writer = csv.writer(response)
    fields = [
        field
        for field in queryset[0]._meta.fields
        if not field.many_to_many and not field.one_to_many
    ]
    # Header
    writer.writerow([field.verbose_name for field in fields])
    # Data
    for obj in queryset:
        data_row = []
        for field in fields:
            value = getattr(obj, field.name)
            data_row.append(value)
        writer.writerow(data_row)
    return response

transactions/templates/transactions/transaction/create.html
{% extends "guest/base.html" %}
{% load i18n %}

{% block title %}{% trans "Transaction" %}{% endblock %}

{% block header %}
  {% include "header_dashboard.html" %}
{% endblock %}

{% block content %}
    {% include "messages.html" %}       
    <div class="container pt-4">
      <div class="col-12 d-flex align-items-center justify-content-center">
        <h2>{% trans "Your transaction:" %}</h2>
      </div>
      <div class="row">
        <div class="col-12 d-flex align-items-center justify-content-center">
          <form method="post" id="transaction-form">
            {{ form.as_p }}
            {% csrf_token %}
            <p><input type="submit" value="{% trans 'Send' %}"></p>
        </form>
        </div>
    </div>
{% endblock %}

transactions/templates/transactions/transaction/detail.html
{% extends "guest/base.html" %}
{% load i18n %}

{% block header %}
    {% include "header_dashboard.html" %}
{% endblock %}

{% block content %}
<div class="container">
    <table class="table table-bordered table-hover text-center mt-2"> 
        <thead>
            <div class="row">
                <tr class="">
                    <th colspan="5">
                        <h1>{% trans "Transaction Details" %}</h1>
                        <a href="{% url 'transaction_pdf' transaction_id=transaction.id  %}">{% trans "Generate PDF" %}</a>
                    </th>
                </tr>
            </div>
            <div class="row">
                <tr>
                    <th scope="col">{% trans "Origin" %}</th>
                    <th scope="col">{% trans "Amount" %}</th>
                    <th scope="col">{% trans "Concept" %}</th>
                    <th scope="col">{% trans "Kind" %}</th>
                    <th scope="col">{% trans "Date" %}</th>
                </tr>
            </div>
        </thead>
        <tbody>
                <tr>
                    <td scope="row">{{ transaction.agent }}</td>
                    <td>{{ transaction.amount }}</td>
                    <td>{{ transaction.concept }}</td>
                    <td>{{ transaction.get_kind_display }}</td>
                    <td>{{ transaction.timestamp|date:"d/m/Y, H:i"  }}</td>
                </tr>                
        </tbody>
    </table>
    <table class="table table-bordered table-hover text-center">
        <thead>
            <th scope="col">{% trans "Comission" %}</th>
            <th scope="col">{% trans "Amount" %}</th>
        </thead>   
        <tbody>             
            {% for comission in transaction.comissions.all %}
                <tr>
                    <td>{{ comission.get_kind_display }}</td>
                    <td>{{ comission.amount }}</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

transactions/templates/transactions/transaction/done.html
{% extends "done_content.html" %}
{% load i18n %}

{% block title %}{% trans "Transfer Done" %}{% endblock %}

{% block heading %}{% trans "Transaction Successful" %}{% endblock %}
{% block secondary_text %}{% trans "Download PDF" %}{% endblock %}
{% block previous_url %}{% url 'transaction_pdf' transaction.id  %}{% endblock %}

transactions/templates/transactions/transaction/error.html
{% extends "done_content.html" %}
{% load i18n %}

{% block title %}{{ error }}{% endblock %}

{% block heading %}{% trans "Error:" %} {{ error }}{% endblock %}
{% block secondary_text %}{% trans "Try Again" %}{% endblock %}
{% block previous_url %}{% url "transfer_out" %}{% endblock %}

transactions/templates/transactions/transaction/pdf.html
{% load i18n %}

<html>
<head>
	{% load bootstrap5 %}
	{% load static %}
    {% load i18n %}
	{% bootstrap_css %}
    <link href="{% static 'css/pdf.css' %}" rel="stylesheet">
</head>
<body>
  <img src="{% static 'img/polaris_logo.png' %}" id="logo">
  <hr>
  <h3>{% trans "Transfer voucher" %}</h3>
  <div class="container">
    <table class="table table-bordered text-center mt-2"> 
        <thead>
            <div class="row">
                <tr>
                    <th scope="col">{% trans "Id" %}</th>
                    <th scope="col">{% trans "Origin" %}</th>
                    <th scope="col">{% trans "Amount" %}</th>
                    <th scope="col">{% trans "Concept" %}</th>
                    <th scope="col">{% trans "Kind" %}</th>
                    <th scope="col">{% trans "Date" %}</th>
                </tr>
            </div>
        </thead>
        <tbody>
                <tr>
                    <td>{{ transaction.id }}</td>
                    <td scope="row">{{ transaction.agent }}</td>
                    <td>{{ transaction.amount }}€</td>
                    <td>{{ transaction.concept }}</td>
                    <td>{{ transaction.get_kind_display }}</td>
                    <td>{{ transaction.timestamp|date:"d/m/Y" }}</td>
                </tr>                
        </tbody>
    </table>
    <table class="table table-bordered text-center">
        <thead>
            <th scope="col">{% trans "Comission" %}</th>
            <th scope="col">{% trans "Amount" %}</th>
        </thead>   
        <tbody>             
            {% for comission in transaction.comissions.all %}
                <tr>
                    <td>{{ comission.get_kind_display  }}</td>
                    <td>{{ comission.amount }}€</td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
</body>
</html>